RetroGames.UI.MVC/Controllers/ConsoleTypesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RetroGames.DATA.EF.Models;

namespace RetroGames.UI.MVC.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ConsoleTypesController : Controller
    {
        private readonly RetroGamesContext _context;

        public ConsoleTypesController(RetroGamesContext context)
        {
            _context = context;
        }

        // GET: ConsoleTypes
        public async Task<IActionResult> Index()
        {
              return _context.ConsoleTypes != null ? 
                          View(await _context.ConsoleTypes.ToListAsync()) :
                          Problem("Entity set 'RetroGamesContext.ConsoleTypes'  is null.");
        }

        // GET: ConsoleTypes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.ConsoleTypes == null)
            {
                return NotFound();
            }

            var consoleType = await _context.ConsoleTypes
                .FirstOrDefaultAsync(m => m.ConsoleTypeId == id);
            if (consoleType == null)
            {
                return NotFound();
            }

            return View(consoleType);
        }

        // GET: ConsoleTypes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ConsoleTypes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ConsoleTypeId,ConsoleName")] ConsoleType consoleType)
        {
            if (ModelState.IsValid)
            {
                _context.Add(consoleType);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(consoleType);
        }

        // GET: ConsoleTypes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.ConsoleTypes == null)
            {
                return NotFound();
            }

            var consoleType = await _context.ConsoleTypes.FindAsync(id);
            if (consoleType == null)
            {
                return NotFound();
            }
            return View(consoleType);
        }

        // POST: ConsoleTypes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ConsoleTypeId,ConsoleName")] ConsoleType consoleType)
        {
            if (id != consoleType.ConsoleTypeId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(consoleType);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ConsoleTypeExists(consoleType.ConsoleTypeId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(consoleType);
        }

        // GET: ConsoleTypes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.ConsoleTypes == null)
            {
                return NotFound();
            }

            var consoleType = await _context.ConsoleTypes
                .FirstOrDefaultAsync(m => m.ConsoleTypeId == id);
            if (consoleType == null)
            {
                return NotFound();
            }

            return View(consoleType);
        }

        // POST: ConsoleTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.ConsoleTypes == null)
            {
                return Problem("Entity set 'RetroGamesContext.ConsoleTypes'  is null.");
            }
            var consoleType = await _context.ConsoleTypes.FindAsync(id);
            if (consoleType != null)
            {
                _context.ConsoleTypes.Remove(consoleType);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ConsoleTypeExists(int id)
        {
          return (_context.ConsoleTypes?.Any(e => e.ConsoleTypeId == id)).GetValueOrDefault();
        }
    }
}

RetroGames.UI.MVC/Views/ConsoleTypes/Create.cshtml
@model RetroGames.DATA.EF.Models.ConsoleType

@{
    ViewData["Title"] = "Create New Console Type";
}

<section class="hero-wrap hero-wrap-2 navbackground" data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text align-items-end justify-content-center">
            <div class="col-md-9 ftco-animate mb-5 text-center">
                <p class="breadcrumbs mb-2"><span class="mr-2"><a href="/">Home <i class="fa fa-chevron-right"></i></a></span> <span class="mr-2"><a href="@Url.Action("Index","ConsoleTypes")">Console Types <i class="fa fa-chevron-right"></i></a></span> <span>@ViewData["Title"] <i class="fa fa-chevron-right"></i></span></p>
                <h2 class="mb-0 bread oldfont">@ViewData["Title"]</h2>
            </div>
        </div>
    </div>
</section>

@*<h4>ConsoleType</h4>*@
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ConsoleName" class="control-label"></label>
                <input asp-for="ConsoleName" class="form-control" />
                <span asp-validation-for="ConsoleName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn button d-inline-flex" />
                <a asp-action="Index" class="btn secondarybutton d-inline-flex">Back to List</a>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RetroGames.UI.MVC/Views/ConsoleTypes/Delete.cshtml
@model RetroGames.DATA.EF.Models.ConsoleType

@{
    ViewData["Title"] = "Delete " + Model.ConsoleName;
}

<section class="hero-wrap hero-wrap-2 navbackground" data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text align-items-end justify-content-center">
            <div class="col-md-9 ftco-animate mb-5 text-center">
                <p class="breadcrumbs mb-2"><span class="mr-2"><a href="/">Home <i class="fa fa-chevron-right"></i></a></span> <span class="mr-2"><a href="@Url.Action("Index","ConsoleTypes")">Console Types <i class="fa fa-chevron-right"></i></a></span> <span>@ViewData["Title"] <i class="fa fa-chevron-right"></i></span></p>
                <h2 class="mb-0 bread oldfont">@ViewData["Title"]</h2>
            </div>
        </div>
    </div>
</section>

<h3>Are you sure you want to delete @Model.ConsoleName?</h3>
<p class="bg-warning text-danger d-inline-block p-3 my-3">
    This action <em>cannot</em> be undone.
</p>
<div>
    @*<h4>ConsoleType</h4>*@
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ConsoleName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ConsoleName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ConsoleTypeId" />
        <input type="submit" value="Delete Forever" class="btn btn-danger d-inline-flex" />
        <a asp-action="Index" class="btn secondarybutton d-inline-flex">Back to List</a>
    </form>
</div>

RetroGames.UI.MVC/Views/ConsoleTypes/Details.cshtml
@model RetroGames.DATA.EF.Models.ConsoleType

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>ConsoleType</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ConsoleName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ConsoleName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.ConsoleTypeId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

RetroGames.UI.MVC/Views/ConsoleTypes/Edit.cshtml
@model RetroGames.DATA.EF.Models.ConsoleType

@{
    ViewData["Title"] = "Edit " + Model.ConsoleName;
}

<section class="hero-wrap hero-wrap-2 navbackground" data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text align-items-end justify-content-center">
            <div class="col-md-9 ftco-animate mb-5 text-center">
                <p class="breadcrumbs mb-2"><span class="mr-2"><a href="/">Home <i class="fa fa-chevron-right"></i></a></span> <span class="mr-2"><a href="@Url.Action("Index","ConsoleTypes")">Console Types <i class="fa fa-chevron-right"></i></a></span> <span>@ViewData["Title"] <i class="fa fa-chevron-right"></i></span></p>
                <h2 class="mb-0 bread oldfont">@ViewData["Title"]</h2>
            </div>
        </div>
    </div>
</section>

@*<h4>ConsoleType</h4>*@
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ConsoleTypeId" />
            <div class="form-group">
                <label asp-for="ConsoleName" class="control-label"></label>
                <input asp-for="ConsoleName" class="form-control" />
                <span asp-validation-for="ConsoleName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn button d-inline-flex" />
                <a asp-action="Index" class="btn secondarybutton d-inline-flex">Back to List</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RetroGames.UI.MVC/Views/ConsoleTypes/Index.cshtml
@model IEnumerable<RetroGames.DATA.EF.Models.ConsoleType>

@{
    ViewData["Title"] = "Console Types";
}


<section class="hero-wrap hero-wrap-2 navbackground" data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text align-items-end justify-content-center">
            <div class="col-md-9 ftco-animate mb-5 text-center">
                <p class="breadcrumbs mb-2"><span class="mr-2"><a href="/">Home <i class="fa fa-chevron-right"></i></a></span> <span>@ViewData["Title"] <i class="fa fa-chevron-right"></i></span></p>
                <h2 class="mb-0 bread oldfont">@ViewData["Title"]</h2>
            </div>
        </div>
    </div>
</section>

<p class="mt-3 ml-2">
    <a asp-action="Create" class="btn button btn-lg">Create New</a>
</p>

<div class="m-3">
    <div class="p-3 bg-light">
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.ConsoleName)
                    </th>
                    <th>Modify</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.ConsoleName)
                        </td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.ConsoleTypeId" class="btn secondarybutton">Edit</a> |
                            @*<a asp-action="Details" asp-route-id="@item.ConsoleTypeId">Details</a> |*@
                            <a asp-action="Delete" asp-route-id="@item.ConsoleTypeId" class="btn btn-danger">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
@section scripts {
    <script>let table = new DataTable('.table');</script>
}