RetroGames.UI.MVC/Controllers/ManufacturersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RetroGames.DATA.EF.Models;

namespace RetroGames.UI.MVC.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ManufacturersController : Controller
    {
        private readonly RetroGamesContext _context;

        public ManufacturersController(RetroGamesContext context)
        {
            _context = context;
        }

        // GET: Manufacturers
        public async Task<IActionResult> Index()
        {
              return _context.Manufacturers != null ? 
                          View(await _context.Manufacturers.ToListAsync()) :
                          Problem("Entity set 'RetroGamesContext.Manufacturers'  is null.");
        }

        // GET: Manufacturers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Manufacturers == null)
            {
                return NotFound();
            }

            var manufacturer = await _context.Manufacturers
                .FirstOrDefaultAsync(m => m.ManufacturerId == id);
            if (manufacturer == null)
            {
                return NotFound();
            }

            return View(manufacturer);
        }

        // GET: Manufacturers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Manufacturers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ManufacturerId,ManufacturerName,ManAddress,ManCity,ManState,ManZip,ManPhone")] Manufacturer manufacturer)
        {
            if (ModelState.IsValid)
            {
                _context.Add(manufacturer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(manufacturer);
        }

        // GET: Manufacturers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Manufacturers == null)
            {
                return NotFound();
            }

            var manufacturer = await _context.Manufacturers.FindAsync(id);
            if (manufacturer == null)
            {
                return NotFound();
            }
            return View(manufacturer);
        }

        // POST: Manufacturers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ManufacturerId,ManufacturerName,ManAddress,ManCity,ManState,ManZip,ManPhone")] Manufacturer manufacturer)
        {
            if (id != manufacturer.ManufacturerId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(manufacturer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ManufacturerExists(manufacturer.ManufacturerId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(manufacturer);
        }

        // GET: Manufacturers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Manufacturers == null)
            {
                return NotFound();
            }

            var manufacturer = await _context.Manufacturers
                .FirstOrDefaultAsync(m => m.ManufacturerId == id);
            if (manufacturer == null)
            {
                return NotFound();
            }

            return View(manufacturer);
        }

        // POST: Manufacturers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Manufacturers == null)
            {
                return Problem("Entity set 'RetroGamesContext.Manufacturers'  is null.");
            }
            var manufacturer = await _context.Manufacturers.FindAsync(id);
            if (manufacturer != null)
            {
                _context.Manufacturers.Remove(manufacturer);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ManufacturerExists(int id)
        {
          return (_context.Manufacturers?.Any(e => e.ManufacturerId == id)).GetValueOrDefault();
        }
    }
}

RetroGames.UI.MVC/Views/Manufacturers/Create.cshtml
@model RetroGames.DATA.EF.Models.Manufacturer

@{
    ViewData["Title"] = "Create a New Manufacturer";
}

<section class="hero-wrap hero-wrap-2 navbackground" data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text align-items-end justify-content-center">
            <div class="col-md-9 ftco-animate mb-5 text-center">
                <p class="breadcrumbs mb-2"><span class="mr-2"><a href="/">Home <i class="fa fa-chevron-right"></i></a></span> <span class="mr-2"><a href="@Url.Action("Index","Manufacturers")">Manufacturers <i class="fa fa-chevron-right"></i></a></span> <span>@ViewData["Title"] <i class="fa fa-chevron-right"></i></span></p>
                <h2 class="mb-0 bread oldfont">@ViewData["Title"]</h2>
            </div>
        </div>
    </div>
</section>

@*<h4>Manufacturer</h4>*@
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ManufacturerName" class="control-label"></label>
                <input asp-for="ManufacturerName" class="form-control" />
                <span asp-validation-for="ManufacturerName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ManAddress" class="control-label"></label>
                <input asp-for="ManAddress" class="form-control" />
                <span asp-validation-for="ManAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ManCity" class="control-label"></label>
                <input asp-for="ManCity" class="form-control" />
                <span asp-validation-for="ManCity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ManState" class="control-label"></label>
                <input asp-for="ManState" class="form-control" />
                <span asp-validation-for="ManState" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ManZip" class="control-label"></label>
                <input asp-for="ManZip" class="form-control" />
                <span asp-validation-for="ManZip" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ManPhone" class="control-label"></label>
                <input asp-for="ManPhone" class="form-control" />
                <span asp-validation-for="ManPhone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn button d-inline-flex" />
                <a asp-action="Index" class="btn secondarybutton d-inline-flex">Back to List</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RetroGames.UI.MVC/Views/Manufacturers/Delete.cshtml
@model RetroGames.DATA.EF.Models.Manufacturer

@{
    ViewData["Title"] = "Delete " + Model.ManufacturerName;
}

<section class="hero-wrap hero-wrap-2 navbackground" data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text align-items-end justify-content-center">
            <div class="col-md-9 ftco-animate mb-5 text-center">
                <p class="breadcrumbs mb-2"><span class="mr-2"><a href="/">Home <i class="fa fa-chevron-right"></i></a></span> <span class="mr-2"><a href="@Url.Action("Index","Manufacturers")">Manufacturers <i class="fa fa-chevron-right"></i></a></span> <span>@ViewData["Title"] <i class="fa fa-chevron-right"></i></span></p>
                <h2 class="mb-0 bread">@ViewData["Title"]</h2>
            </div>
        </div>
    </div>
</section>

<h3>Are you sure you want to delete @Model.ManufacturerName?</h3>
<div>
    @*<h4>Manufacturer</h4>*@
    <p class="bg-warning text-danger d-inline-block p-3 my-3">
        This action <em>cannot</em> be undone.
    </p>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ManufacturerName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ManufacturerName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ManAddress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ManAddress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ManCity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ManCity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ManState)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ManState)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ManZip)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ManZip)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ManPhone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ManPhone)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ManufacturerId" />
        <input type="submit" value="Delete Forever" class="btn btn-danger d-inline-flex" />
        <a asp-action="Index" class="btn secondarybutton d-inline-flex">Back to List</a>
    </form>
</div>

RetroGames.UI.MVC/Views/Manufacturers/Details.cshtml
@model RetroGames.DATA.EF.Models.Manufacturer

@{
    ViewData["Title"] = Model.ManufacturerName + " Details";
}

<section class="hero-wrap hero-wrap-2 navbackground" data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text align-items-end justify-content-center">
            <div class="col-md-9 ftco-animate mb-5 text-center">
                <p class="breadcrumbs mb-2"><span class="mr-2"><a href="/">Home<i class="fa fa-chevron-right"></i></a></span><span><a href="@Url.Action("Index", "Manufacturers")">Manufacturers<i class="fa fa-chevron-right"></i></a></span> <span>@ViewData["Title"]<i class="fa fa-chevron-right"></i></span></p>
                <h2 class="mb-0 bread oldfont">@ViewData["Title"]</h2>
            </div>
        </div>
    </div>
</section>

<div>
    <h4>Manufacturer</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ManufacturerName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ManufacturerName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ManAddress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ManAddress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ManCity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ManCity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ManState)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ManState)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ManZip)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ManZip)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ManPhone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ManPhone)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.ManufacturerId" class="btn button d-inline-flex">Edit</a>
    <a asp-action="Index" class="btn secondarybutton d-inline-flex">Back to List</a>
    <a asp-action="Delete" asp-route-id="@Model.ManufacturerId" class="btn btn-danger d-inline-flex">Delete</a>
</div>

RetroGames.UI.MVC/Views/Manufacturers/Edit.cshtml
@model RetroGames.DATA.EF.Models.Manufacturer

@{
    ViewData["Title"] = "Edit " + Model.ManufacturerName;
}

<section class="hero-wrap hero-wrap-2 navbackground" data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text align-items-end justify-content-center">
            <div class="col-md-9 ftco-animate mb-5 text-center">
                <p class="breadcrumbs mb-2"><span class="mr-2"><a href="/">Home <i class="fa fa-chevron-right"></i></a></span> <span class="mr-2"><a href="@Url.Action("Index","Manufacturers")">Manufacturers <i class="fa fa-chevron-right"></i></a></span> <span>@ViewData["Title"] <i class="fa fa-chevron-right"></i></span></p>
                <h2 class="mb-0 bread oldfont">@ViewData["Title"]</h2>
            </div>
        </div>
    </div>
</section>

@*<h4>Manufacturer</h4>*@
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ManufacturerId" />
            <div class="form-group">
                <label asp-for="ManufacturerName" class="control-label"></label>
                <input asp-for="ManufacturerName" class="form-control" />
                <span asp-validation-for="ManufacturerName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ManAddress" class="control-label"></label>
                <input asp-for="ManAddress" class="form-control" />
                <span asp-validation-for="ManAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ManCity" class="control-label"></label>
                <input asp-for="ManCity" class="form-control" />
                <span asp-validation-for="ManCity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ManState" class="control-label"></label>
                <input asp-for="ManState" class="form-control" />
                <span asp-validation-for="ManState" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ManZip" class="control-label"></label>
                <input asp-for="ManZip" class="form-control" />
                <span asp-validation-for="ManZip" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ManPhone" class="control-label"></label>
                <input asp-for="ManPhone" class="form-control" />
                <span asp-validation-for="ManPhone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn button d-inline-flex" />
                <a asp-action="Index" class="btn secondarybutton d-inline-flex">Back to List</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RetroGames.UI.MVC/Views/Manufacturers/Index.cshtml
@model IEnumerable<RetroGames.DATA.EF.Models.Manufacturer>

@{
    ViewData["Title"] = "Manufacturers";
}

<section class="hero-wrap hero-wrap-2 navbackground" data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text align-items-end justify-content-center">
            <div class="col-md-9 ftco-animate mb-5 text-center">
                <p class="breadcrumbs mb-2"><span class="mr-2"><a href="/">Home <i class="fa fa-chevron-right"></i></a></span> <span>@ViewData["Title"] <i class="fa fa-chevron-right"></i></span></p>
                <h2 class="mb-0 bread oldfont">@ViewData["Title"]</h2>
            </div>
        </div>
    </div>
</section>

<p class="mt-3 ml-2">
    <a asp-action="Create" class="btn button btn-lg">Create New</a>
</p>

<div class="m-3">
    <div class="p-3 bg-light">
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.ManufacturerName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.ManAddress)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.ManCity)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.ManState)
                    </th>
                    <th>Modify</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td class="tname">
                            <a asp-action="Details" asp-route-id="@item.ManufacturerId">
                            @Html.DisplayFor(modelItem => item.ManufacturerName)
                            </a>
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ManAddress)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ManCity)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ManState)
                        </td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.ManufacturerId" class="btn secondarybutton">Edit</a> |
                            <a asp-action="Delete" asp-route-id="@item.ManufacturerId" class="btn btn-danger">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
@section scripts {
    <script>let table = new DataTable('.table');</script>
}