RetroGames.UI.MVC/Controllers/OrdersController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RetroGames.DATA.EF.Models;
using RetroGames.UI.MVC.Models;

namespace RetroGames.UI.MVC.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private readonly RetroGamesContext _context;

        public OrdersController(RetroGamesContext context)
        {
            _context = context;
        }

        // GET: Orders
        [Authorize]
        public async Task<IActionResult> Index()
        {
            if (!User.IsInRole("Admin"))
            {
                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

                var retroGamesContext = _context.Orders.Include(o => o.User).Where(o => o.UserId == userId);
                return View(await retroGamesContext.ToListAsync());
            }

            var adminRetroGamesContext = _context.Orders.Include(o => o.User);
            return View(await adminRetroGamesContext.ToListAsync());

        }

        // GET: Orders/Details/5
        [Authorize]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Orders == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .Include(o => o.User).Include(op => op.OrderProducts).ThenInclude(p => p.Product)
                .FirstOrDefaultAsync(m => m.OrderId == id);
            if (order == null)
            {
                return NotFound();
            }

            // Retrieve the success message from TempData (if available)
            string successMessage = TempData["SuccessMessage"] as string;

            // Pass the order details and success message to the view
            ViewData["Order"] = order;
            ViewData["SuccessMessage"] = successMessage;

            return View(order);
        }

        // GET: Orders/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            ViewData["UserId"] = new SelectList(_context.Users, "UserId", "UserId");
            return View();
        }

        // POST: Orders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("OrderId,UserId,OrderDate,ShipToName,ShipCity,ShipState,ShipZip")] Order order)
        {
            if (ModelState.IsValid)
            {
                _context.Add(order);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.Users, "UserId", "UserId", order.UserId);
            return View(order);
        }

        // GET: Orders/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Orders == null)
            {
                return NotFound();
            }

            var order = await _context.Orders.FindAsync(id);
            if (order == null)
            {
                return NotFound();
            }
            ViewData["UserId"] = new SelectList(_context.Users, "UserId", "UserId", order.UserId);
            return View(order);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("OrderId,UserId,OrderDate,ShipToName,ShipCity,ShipState,ShipZip")] Order order)
        {
            if (id != order.OrderId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(order);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderExists(order.OrderId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.Users, "UserId", "UserId", order.UserId);
            return View(order);
        }

        // GET: Orders/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Orders == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .Include(o => o.User)
                .FirstOrDefaultAsync(m => m.OrderId == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // POST: Orders/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Orders == null)
            {
                return Problem("Entity set 'RetroGamesContext.Orders'  is null.");
            }
            var order = await _context.Orders.FindAsync(id);
            if (order != null)
            {
                _context.Orders.Remove(order);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrderExists(int id)
        {
          return (_context.Orders?.Any(e => e.OrderId == id)).GetValueOrDefault();
        }
    }
}

RetroGames.UI.MVC/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RetroGames.DATA.EF.Models;
using Microsoft.AspNetCore.Authorization;
using System.Data;
using RetroGames.UI.MVC.Utilities;
using System.Drawing;
using X.PagedList;

namespace RetroGames.UI.MVC.Controllers
{


    [Authorize(Roles = "Admin")]
    public class ProductsController : Controller
    {
        private readonly RetroGamesContext _context;

        private readonly IWebHostEnvironment _webHostEnvironment;

        public ProductsController(RetroGamesContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        // GET: Products
        [AllowAnonymous]
        public async Task<IActionResult> OriginalIndex()
        {
            if (User.IsInRole("Admin"))
            {
                var products = _context.Products.Include(p => p.Category).Include(p => p.ConsoleType).Include(p => p.Genre).Include(p => p.Manufacturer);
                return View(await products.ToListAsync());
            }
            else
            {
                var products = _context.Products.Where(p => p.IsDiscontinued == false && p.UnitsInStock > 0)
                    .Include(p => p.Category).Include(p => p.ConsoleType).Include(p => p.Genre).Include(p => p.Manufacturer);
                return View(await products.ToListAsync());
            }
            
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index(string searchTerm, int categoryId = 0, int page = 1)
        {
            int pageSize = 12;

            var products = _context.Products.Where(p => !p.IsDiscontinued)
                .Include(p => p.Category)
                .Include(p => p.Manufacturer)
                .Include(p => p.OrderProducts).ToList();

            #region Category Filter

            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryName");

            ViewBag.Category = 0;

            if(categoryId != 0)
            {
                products = products.Where(p => p.CategoryId == categoryId).ToList();

                //Repopulate the dropdown with the current category selected
                ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryName", categoryId);

                ViewBag.Category = categoryId;
            }
            #endregion

            #region Search Filter

            if (!String.IsNullOrEmpty(searchTerm))
            {
                products = products.Where(p =>
                p.ProductName.ToLower().Contains(searchTerm.ToLower()) ||
                p.Manufacturer.ManufacturerName.ToLower().Contains(searchTerm.ToLower()) ||
                p.Category.CategoryName.ToLower().Contains(searchTerm.ToLower()) ||
                p.ProductDescription.ToLower().Contains(searchTerm.ToLower())).ToList();

                ViewBag.NbrResults = products.Count;

                ViewBag.SearchTerm = searchTerm;
            }
            else
            {
                ViewBag.NbrResults = null;
                ViewBag.SearchTerm = null;
            }

            #endregion
            return View(products.ToPagedList(page, pageSize));
        }

        // GET: Products/Details/5
        [AllowAnonymous]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Products == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Category)
                .Include(p => p.ConsoleType)
                .Include(p => p.Genre)
                .Include(p => p.Manufacturer)
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Products/Create
        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryName");
            ViewData["ConsoleTypeId"] = new SelectList(_context.ConsoleTypes, "ConsoleTypeId", "ConsoleName");
            ViewData["GenreId"] = new SelectList(_context.Genres, "GenreId", "GenreName");
            ViewData["ManufacturerId"] = new SelectList(_context.Manufacturers, "ManufacturerId", "ManufacturerName");
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProductId,ProductName,ProductPrice,ReleaseDate,ProductDescription,UnitsInStock,ConsoleTypeId,ManufacturerId,CategoryId,GenreId,IsDiscontinued,ProductImage,ImageFile")] Product product)
        {
            if (ModelState.IsValid)
            {

                #region File Upload - Create w/Image Utility
                if (product.ImageFile != null)
                {
                    //process file

                    //check the file type
                    // - retrieve the extension of the uploaded file
                    string ext = Path.GetExtension(product.ImageFile.FileName);

                    // - Create a list of valid extensions
                    string[] validExts = { ".jpg", "jpeg", ".gif", ".png" };

                    // - Check the file extension against the list of valid extensions
                    if (validExts.Contains(ext.ToLower()) && product.ImageFile.Length < 4_194_303)//less than for megabytes as well.
                    {
                        // Generate a unique filename
                        product.ProductImage = Guid.NewGuid() + ext;

                        //Save the file to the web server (here it's saved to wwwroot/images)
                        // - retrieve the path to wwwroot
                        string webRootPath = _webHostEnvironment.WebRootPath;

                        // - create a variable for the full image path
                        string fullImagePath = webRootPath + "/images/";

                        // Create a MemoryStream to read the image into our web server's memory
                        using (var memoryStream = new MemoryStream())
                        {
                            await product.ImageFile.CopyToAsync(memoryStream);
                            using (var img = Image.FromStream(memoryStream))
                            {
                                //now, send the image to the ImageUtility for resizing and saving
                                //need 5 arguments for the utility to resize our image...
                                //1) (int) maximum image size
                                //2) (int) maximum thumbnail size
                                //3) (string) full path where the file will be saved
                                //4) (Image) an image
                                //5) (string) filename

                                int maxImageSize = 500;
                                int maxThumbSize = 100;

                                ImageUtility.ResizeImage(fullImagePath, product.ProductImage, img, maxImageSize, maxThumbSize);
                            }
                        }
                    }

                }
                else
                {
                    //assign a default image
                    //If no image was uploaded, assign a default filename
                    //Will also need to download a default image and name it 'noimage.png' -> place it in the wwwroot/images
                    product.ProductImage = "noimage.png";
                }
                #endregion

                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryName", product.CategoryId);
            ViewData["ConsoleTypeId"] = new SelectList(_context.ConsoleTypes, "ConsoleTypeId", "ConsoleName", product.ConsoleTypeId);
            ViewData["GenreId"] = new SelectList(_context.Genres, "GenreId", "GenreName", product.GenreId);
            ViewData["ManufacturerId"] = new SelectList(_context.Manufacturers, "ManufacturerId", "ManufacturerName", product.ManufacturerId);
            return View(product);
        }

        // GET: Products/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Products == null)
            {
                return NotFound();
            }

            var product = await _context.Products.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryName", product.CategoryId);
            ViewData["ConsoleTypeId"] = new SelectList(_context.ConsoleTypes, "ConsoleTypeId", "ConsoleName", product.ConsoleTypeId);
            ViewData["GenreId"] = new SelectList(_context.Genres, "GenreId", "GenreName", product.GenreId);
            ViewData["ManufacturerId"] = new SelectList(_context.Manufacturers, "ManufacturerId", "ManufacturerName", product.ManufacturerId);
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]

RetroGames.UI.MVC/Views/Orders/Create.cshtml
@model RetroGames.DATA.EF.Models.Order

@{
    ViewData["Title"] = "Create";
}

<section class="hero-wrap hero-wrap-2 navbackground" data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text align-items-end justify-content-center">
            <div class="col-md-9 ftco-animate mb-5 text-center">
                <p class="breadcrumbs mb-2"><span class="mr-2"><a href="/">Home <i class="fa fa-chevron-right"></i></a></span> <span class="mr-2"><a href="@Url.Action("Index","Orders")">Orders <i class="fa fa-chevron-right"></i></a></span> <span>@ViewData["Title"] <i class="fa fa-chevron-right"></i></span></p>
                <h2 class="mb-0 bread oldfont">@ViewData["Title"]</h2>
            </div>
        </div>
    </div>
</section>

@*<h4>Order</h4>*@
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <select asp-for="UserId" class ="form-control" asp-items="ViewBag.UserId"></select>
            </div>
            <div class="form-group">
                <label asp-for="OrderDate" class="control-label"></label>
                <input asp-for="OrderDate" class="form-control" />
                <span asp-validation-for="OrderDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShipToName" class="control-label"></label>
                <input asp-for="ShipToName" class="form-control" />
                <span asp-validation-for="ShipToName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShipCity" class="control-label"></label>
                <input asp-for="ShipCity" class="form-control" />
                <span asp-validation-for="ShipCity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShipState" class="control-label"></label>
                <input asp-for="ShipState" class="form-control" />
                <span asp-validation-for="ShipState" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShipZip" class="control-label"></label>
                <input asp-for="ShipZip" class="form-control" />
                <span asp-validation-for="ShipZip" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn button" />
            </div>
        </form>
    </div>
</div>

<div class="mb-3">
    <a asp-action="Index" class="btn secondarybutton">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RetroGames.UI.MVC/Views/Orders/Delete.cshtml
@model RetroGames.DATA.EF.Models.Order

@{
    ViewData["Title"] = "Delete Order #" + Model.OrderId;
}

<section class="hero-wrap hero-wrap-2 navbackground" data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text align-items-end justify-content-center">
            <div class="col-md-9 ftco-animate mb-5 text-center">
                <p class="breadcrumbs mb-2"><span class="mr-2"><a href="/">Home <i class="fa fa-chevron-right"></i></a></span> <span class="mr-2"><a href="@Url.Action("Index","Orders")">Orders <i class="fa fa-chevron-right"></i></a></span> <span>@ViewData["Title"] <i class="fa fa-chevron-right"></i></span></p>
                <h2 class="mb-0 bread oldfont">@ViewData["Title"]</h2>
            </div>
        </div>
    </div>
</section>

<h3>Are you sure you want to delete this?</h3>
<div>
    @*<h4>Order</h4>*@
    <p class="bg-warning text-danger d-inline-block p-3 my-3">
        This action <em>cannot</em> be undone.
    </p>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OrderDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OrderDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ShipToName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ShipToName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ShipCity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ShipCity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ShipState)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ShipState)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ShipZip)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ShipZip)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.UserId)
        </dd>
    </dl>
    
    <form asp-action="Delete" class="mb-3">
        <input type="hidden" asp-for="OrderId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn secondarybutton">Back to List</a>
    </form>
</div>

RetroGames.UI.MVC/Views/Orders/Details.cshtml
@model RetroGames.DATA.EF.Models.Order

@{
    ViewData["Title"] = "Details for Order #" + Model.OrderId;
    decimal? total = 0;
}

<section class="hero-wrap hero-wrap-2 navbackground" data-stellar-background-ratio="0.5">
    @*<div class="overlay"></div>*@
    <div class="container">
        <div class="row no-gutters slider-text align-items-end justify-content-center">
            <div class="col-md-9 ftco-animate mb-5 text-center">
                <p class="breadcrumbs mb-2"><span class="mr-2"><a href="/">Home <i class="fa fa-chevron-right"></i></a></span> <span class="mr-2"><a href="@Url.Action("Index","Orders")">Orders <i class="fa fa-chevron-right"></i></a></span> <span>@ViewData["Title"] <i class="fa fa-chevron-right"></i></span></p>
                <h2 class="mb-0 bread oldfont">@ViewData["Title"]</h2>
            </div>
        </div>
    </div>
</section>

<section class="p-5">
    <div class="Container bg-light p-4">
        @if (!string.IsNullOrEmpty(ViewData["SuccessMessage"] as string))
        {
            <div class="alert alert-success">@ViewData["SuccessMessage"]</div>
        }
        <div class="d-flex justify-content-between align-items-center">
            <div>
                <h3>Retro Games</h3>
                <h4>Order #@Model.OrderId</h4>
            </div>
            <dl class="row w-25 text-dark mr-0">
                <dt class="col-sm-2 col-md-4 text-right">
                    @Html.DisplayNameFor(model => model.ShipToName)
                </dt>
                <dd class="col-sm-10 col-md-8 pr-0">
                    @($"{Model.User.FirstName} {Model.User.LastName}")
                </dd>
                <dt class="col-sm-2 col-md-4 text-right">
                    @Html.DisplayNameFor(model => model.User.Address)
                </dt>
                <dd class="col-sm-10 col-md-8 pr-0">
                    @Html.DisplayFor(model => model.User.Address) <br />
                    @Html.DisplayFor(model => model.ShipCity), @Html.DisplayFor(model => model.ShipState) @Html.DisplayFor(model => model.ShipZip)
                </dd>
            </dl>
        </div>
        <div class="text-center d-flex justify-content-center">
            <div class="table-wrap vw-100">
                <table class="table w-85">
                    <thead>
                        <tr>
                            <th></th>
                            <th>Quantity</th>
                            <th class="text-left">Product Name</th>
                            <th>Price</th>
                            <th>Total</th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (var item in Model.OrderProducts)
                        {
                            decimal? itemTotal = item.Quantity * item.ProductPrice;
                            total += itemTotal;
                            <tr>
                                <td class="py-2"><img src="~/images/t_@item.Product.ProductImage" class="img-fluid" alt="@item.Product.ProductName" /></td>
                                <td class="py-2">@item.Quantity</td>
                                <td class="text-left py-2"><a asp-action="Details" asp-controller="Products" asp-route-id="@item.Product.ProductId" class="text-dark">@item.Product.ProductName</a></td>

                                <td class="py-2">@string.Format("{0:C}",item.ProductPrice)</td>
                                <td class="py-2">@string.Format("{0:C}",(itemTotal))</td>
                            </tr>

                        }
                    </tbody>
                </table>
            </div>
            
        </div>

        <div class="row d-flex justify-content-end">
            <div class="col col-lg-5 col-md-6 mt-5 cart-wrap ftco-animate">
                <div class="cart-total mb-3 bg-white">
                    <h3>Order Totals</h3>
                    <p class="d-flex">
                        <span>Subtotal</span>
                        <span>@string.Format($"{total:c}")</span>
                    </p>
                    <p class="d-inline-flex">
                        <span m-0>Delivery</span>
                        @if (total >= 30)
                        {
                            <span class="d-flex">Free Delivery!</span>
                        }
                        else
                        {
                            decimal? delivery = (5 * total) / 100;

                            <span>@string.Format($"{delivery:c}")</span>

                            total += delivery;
                        }
                    </p>
                    <hr>
                    <p class="d-flex total-price">
                        <span>Total</span>
                        <span>@string.Format($"{total:c}")</span>
                    </p>
                </div>

            </div>
        </div>
    </div>
</section>

@*<div>
    <h4>Order</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OrderDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OrderDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ShipToName)
            Ship To
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ShipToName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ShipCity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ShipCity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ShipState)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ShipState)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ShipZip)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ShipZip)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.FirstName)
            @ViewBag.FullName
        </dd>
    </dl>
</div>*@

@if (User.IsInRole("Admin"))
{
    <div class="mb-3">
        <a asp-action="Edit" asp-route-id="@Model?.OrderId" class="btn button">Edit</a><span>|</span>
        <a asp-action="Index" class="btn secondarybutton">Back to List</a>
    </div>
}


@*@section scripts {
    <script>let table = new DataTable('.table');</script>

}*@

RetroGames.UI.MVC/Views/Orders/Edit.cshtml
@model RetroGames.DATA.EF.Models.Order

@{
    ViewData["Title"] = "Edit Order #" + Model.OrderId;
}

<section class="hero-wrap hero-wrap-2 navbackground" data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text align-items-end justify-content-center">
            <div class="col-md-9 ftco-animate mb-5 text-center">
                <p class="breadcrumbs mb-2"><span class="mr-2"><a href="/">Home <i class="fa fa-chevron-right"></i></a></span> <span class="mr-2"><a href="@Url.Action("Index","Orders")">Orders <i class="fa fa-chevron-right"></i></a></span> <span>@ViewData["Title"] <i class="fa fa-chevron-right"></i></span></p>
                <h2 class="mb-0 bread oldfont">@ViewData["Title"]</h2>
            </div>
        </div>
    </div>
</section>

@*<h4>Order</h4>*@
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="OrderId" />
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <select asp-for="UserId" class="form-control" asp-items="ViewBag.UserId"></select>
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrderDate" class="control-label"></label>
                <input asp-for="OrderDate" class="form-control" />
                <span asp-validation-for="OrderDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShipToName" class="control-label"></label>
                <input asp-for="ShipToName" class="form-control" />
                <span asp-validation-for="ShipToName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShipCity" class="control-label"></label>
                <input asp-for="ShipCity" class="form-control" />
                <span asp-validation-for="ShipCity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShipState" class="control-label"></label>
                <input asp-for="ShipState" class="form-control" />
                <span asp-validation-for="ShipState" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShipZip" class="control-label"></label>
                <input asp-for="ShipZip" class="form-control" />
                <span asp-validation-for="ShipZip" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn button" />
            </div>
        </form>
    </div>
</div>

<div class="mb-3">
    <a asp-action="Index" class="btn secondarybutton">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}